### PR TITLE
Feature/adifeature

### PR DESCRIPTION
**Pull request by adigudi**
Here is a picture of my progress bar:

Screen Shot 2020-09-07 at 7 13 49 PM

### CODE REVIEW

**Review by ChaoticLeah — DISMISSED** [review]
CurrentValue is set twice, once in start() and once where its defined. Might want to make a function to add/subtract the inputted amount. Also, this thing called "Foreground Border" makes it hard to see the bar, you can set the image to none, and set the background color to transparent to fix this.

**Comment by Ryguy-1** [comment]
I agree with Kevin about adding methods to add/subtract, along with making the bar filling easier to see. In addition, maybe consider relocating the bar to somewhere else like in a top corner of the screen. I like the animation, and would suggest you keep this in the future, so keeping this "animation" when you make add or subtract methods would be nice as well.

**Comment by ChaoticLeah** [comment]
This is what I got when making the background of the text invisible:
image

**Comment by buttercakeee** [comment]
I personally think that maybe the percent shouldn't have a decimal, or if it does, there should only be one decimal point. I also like the general idea, but maybe add a border around the bar so even when it's full there's like a black border or something? Aesthetically, I feel like it would make it stand out a bit more and be a bit more defined. To be honest, I like the initial design better.

**Comment by eanewman** [comment]
I just noticed that you have a conflict in the README file - if you don't want to include the changes to that file you can remove them.

**Review by ChaoticLeah — APPROVED** [review]

**Pull request merged**
